on:
  push:
    branches:
      - main
    paths-ignore:
      - .idea
      - CDC1.pdf
      - CDC2.pdf
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        target:
          - client
          - server
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ghcr.io/${{ github.repository }}/${{ matrix.target }}
          flavor: |
            latest=true
          tags: |
            type=sha,format=long,prefix=
      - uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.target }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p -m 700 ~/.ssh
      - run: eval $(ssh-agent -s)
      - run: echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        env:
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      - run: chmod 600 ~/.ssh/id_ed25519 ~/.ssh/known_hosts
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker stack deploy -c ollarrive-stack.yml --with-registry-auth ollarrive
        working-directory: ci/
        env:
          BASE_IMAGE: ghcr.io/${{ github.repository }}
          DOCKER_HOST: ${{ vars.DOCKER_HOST }}
          TAG: ${{ github.sha }}
